# Generated by Django 5.1.2 on 2024-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0002_alter_country_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='airports',
            field=models.ManyToManyField(blank=True, to='core.airport'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cities',
            field=models.ManyToManyField(blank=True, to='core.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='continents',
            field=models.ManyToManyField(blank=True, to='core.continent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='countries',
            field=models.ManyToManyField(blank=True, to='core.country'),
        ),
    ]
