# Generated by Django 5.1.2 on 2024-11-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(default=1),
        ),
    ]
